services:
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
